### ISSUE TITLE
Stopped working on Cloudflare Worker

### ISSUE THREAD

**Issue by sumiren** [tidbcloud/serverless-js#63]
I've  been encountering an error on Cloudflare Workers that started appearing around May 11.
Since this issue is occurring across multiple products, I suspect that it's related to an incompatibility between some update on the Cloudflare Workers side and this library.
```
"logs": [
  {
    "message": [
      "TypeError: Unsupported cache mode: no-store"
    ],
    "level": "error",
    "timestamp": 1715489591388
  }
],
```

I tried replacing `fetchCacheOption` empty object in node_modules and deploying to Cloudflare Workers, and confirmed the error disappears. 
https://github.com/tidbcloud/serverless-js/blob/efc89f151920219d138befcfde56cca0cb2df527/src/serverless.ts#L5

I'm not sure if this issue should be addressed on the TiDB side, but I wanted to share the problem with you first. Thanks.

**Comment by bohnen** [comment]
I found that the logic for judging whether it can use the cache option does not work for the current Cloudflare worker.
https://github.com/tidbcloud/serverless-js/blob/efc89f151920219d138befcfde56cca0cb2df527/src/serverless.ts#L8

Creating a new Request object doesn't throw an exception. It seems that only when calling fetch with this Request object throws an exception.

**Comment by zhangyangyu** [comment]
@sumiren thanks for reporting. The linked issue shows Cloudflare Worker has rolled out something new and break our driver. They are rolling back and we're also going to catch up what's new there.

**Comment by jasnell** [comment]
Our plan in workers is to implement Request.cache 'no-store' and 'no-cache' and this was a first step. We'll be rolling back this change and putting it behind a compatibility flag/date.

**Comment by sumiren** [comment]
@jasnell 
Thanks! I saw your actions on [the issue](https://github.com/cloudflare/workerd/issues/2116) on `cloudflare/workerd` and confirmed that my problem has been solved.

@zhangyangyu @bohnen 
Thanks to you and the Cloudflare team, my issue has been resolved now. Could I leave the decision on what to do with this issue up to you?
Thank you for your assistance!

**Comment by zhangyangyu** [comment]
@sumiren I am going to close this issue and leave the driver unchanged now. Once Cloudflare Worker has published the new cache flag, we'll catch up. Thanks for your report!

**Comment by AdityaAtulTewari** [comment]
@sumiren we are about to reroll out this change we added tests for the behavior you described but we'd like to actively monitor your workers as we deploy them. Could you tell us the zone name of the worker that broke?
