### ISSUE TITLE
lastInsertId not correct with AUTO_RANDOM id

### ISSUE THREAD

**Issue by lucklove** [tidbcloud/serverless-js#65]
```sql
CREATE TABLE `t` (
  `id` BIGINT NOT NULL AUTO_RANDOM,
  `name` varchar(128) NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

```
const tx = await conn.begin()

const r = await tx.execute(
    "insert into t (name) values (?)",
    ["banana"],
    { fullResult: true },
)

console.log(r.lastInsertId)
```

The output will be something like `3746994889972252700` (multiple of 100) but the real id is `3746994889972252673`

**Comment by shiyuhang0** [comment]
Thanks for your report.
Seems there is a precision loss for `lastInsertId`. I will take a deep look tomorrow.

**Comment by shiyuhang0** [comment]
lastInsertId will lose precision when it exceeds the MAX_SAFE_INTEGER of the number type

After some research, we decide to change the type of lastInsertId to string in https://github.com/tidbcloud/serverless-js/pull/66. It will be a break change and we will release v0.2.0 after pr is merged

**Comment by shiyuhang0** [comment]
Close as it has been resolved. Please reopen it if have any questions
