### ISSUE TITLE
"connect" cannot be used for local tidb.

### ISSUE THREAD

**Issue by MasanoriOnishi** [tidbcloud/serverless-js#68]
I want to use connect of serverless-js in local development. But now it doesn't work.

I use tiup for using tidb in local environment.
https://github.com/ti-click/docker-tidb-playground

And I ran this code.
```
const connection = connect({url : "mysql://root@localhost:4000/test"})
const results = await conn.execute('select * from test where id = ?',[1])
```

But I bumped into this error
```
 [TypeError: fetch failed] {
  cause:  [Error: getaddrinfo ENOTFOUND http-localhost] {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http-localhost'
}
```

Is there any workaround for this?

**Comment by zhangyangyu** [comment]
Hi @MasanoriOnishi , serverless-js is limited to TiDB Serverless, not able to use with TiDB Dedicated and TiDB local deployment now. For TiDB dedicated and local deployment, you need to use a JavaScript MySQL driver like mysql2.

**Comment by MasanoriOnishi** [comment]
@zhangyangyu Thank you for your advice.
I'll try another mysql driver.
